#pragma once
#include <stdint.h>

enum team : uint8_t {
    team_none = 0,
    team_tr   = 1,
    team_ct   = 2,
    team_spec = 3,
};

enum view_mode: uint8_t {
    view_mode_none = 0,
    view_mode_fps  = 1,
    view_mode_tps  = 2,
};

enum observation_state : uint8_t {
	observation_state_none      = 0,
	observation_state_invisible = 1,
	observation_state_visible   = 2,
};

enum weapon_id : uint8_t {
    weapon_id_none = 0,
	weapon_id_g22 = 11,
	weapon_id_usp = 12,
	weapon_id_p350 = 13,
	weapon_id_deagle = 15,
	weapon_id_tec9 = 16,
	weapon_id_fiveseven = 17,
	weapon_id_berettas = 18,
	weapon_id_ump45 = 32,
	weapon_id_mp7 = 34,
	weapon_id_p90 = 35,
	weapon_id_mp5 = 36,
	weapon_id_mac10 = 37,
	weapon_id_val = 42,
	weapon_id_m4a1 = 43,
	weapon_id_akr = 44,
	weapon_id_akr12 = 45,
	weapon_id_m4 = 46,
	weapon_id_m16 = 47,
	weapon_id_famas = 48,
	weapon_id_fnfal = 49,
	weapon_id_awm = 51,
	weapon_id_m40 = 52,
	weapon_id_m110 = 53,
	weapon_id_sm1014 = 62,
	weapon_id_fabm = 63,
	weapon_id_m60 = 64,
	weapon_id_spas = 65,
	weapon_id_knife = 70,
	weapon_id_knife_bayonet = 71,
	weapon_id_knife_karambit = 72,
	weapon_id_knife_jkommando = 73,
	weapon_id_knife_butterfly = 75,
	weapon_id_knife_flip = 77,
	weapon_id_knife_kunai = 78,
	weapon_id_knife_scorpion = 79,
	weapon_id_knife_tanto = 80,
	weapon_id_knife_daggers = 81,
	weapon_id_knife_kukri = 82,
	weapon_id_knife_stiletto = 83,
	weapon_id_knife_fang = 86,
	weapon_id_knife_sting = 88,
	weapon_id_grenade_he = 91,
	weapon_id_grenade_smoke = 92,
	weapon_id_grenade_flash = 93,
	weapon_id_grenade_molotov = 94,
	weapon_id_grenade_incendiary = 95,
	weapon_id_bomb = 100,
	weapon_id_defuser = 101,
	weapon_id_defuse_kit = 102,
	weapon_id_vest = 110,
	weapon_id_vest_and_helmet = 111,
};

enum weapon_type : uint8_t {
	weapon_type_none = 0,
	weapon_type_pistol = 1,
	weapon_type_smg = 2,
	weapon_type_rifle = 3,
	weapon_type_shotgun = 4,
	weapon_type_heavy = 5,
	weapon_type_sniper = 6,
	weapon_type_grenade = 7,
	weapon_type_knife = 8,
};

enum bip : uint8_t {
	bip_head,
	bip_neck,
	bip_spine,
	bip_spine1,
	bip_spine2,
	bip_left_shoulder,
	bip_left_upperarm,
	bip_left_forearm,
	bip_left_hand,
	bip_right_shoulder,
	bip_right_upperarm,
	bip_right_forearm,
	bip_right_hand,
	bip_hip,
	bip_left_up_leg,
	bip_left_leg,
	bip_left_foot,
	bip_left_toe_base,
	bip_right_up_leg,
	bip_right_leg,
	bip_right_foot,
	bip_right_toe_base,
	bip_left_in_hand_index,
	bip_left_hand_index1,
	bip_left_hand_index2,
	bip_left_hand_index3,
	bip_left_hand_index4,
	bip_left_in_hand_middle,
	bip_left_hand_middle1,
	bip_left_hand_middle2,
	bip_left_hand_middle3,
	bip_left_hand_middle4,
	bip_left_in_hand_pinky,
	bip_left_hand_pinky1,
	bip_left_hand_pinky2,
	bip_left_hand_pinky3,
	bip_left_hand_pinky4,
	bip_left_in_hand_ring,
	bip_left_hand_ring1,
	bip_left_hand_ring2,
	bip_left_hand_ring3,
	bip_left_hand_ring4,
	bip_left_in_hand_thumb,
	bip_left_hand_thumb1,
	bip_left_hand_thumb2,
	bip_left_hand_thumb3,
	bip_right_in_hand_index,
	bip_right_hand_index1,
	bip_right_hand_index2,
	bip_right_hand_index3,
	bip_right_hand_index4,
	bip_right_in_hand_middle,
	bip_right_hand_middle1,
	bip_right_hand_middle2,
	bip_right_hand_middle3,
	bip_right_hand_middle4,
	bip_right_in_hand_pinky,
	bip_right_hand_pinky1,
	bip_right_hand_pinky2,
	bip_right_hand_pinky3,
	bip_right_hand_pinky4,
	bip_right_in_hand_ring,
	bip_right_hand_ring1,
	bip_right_hand_ring2,
	bip_right_hand_ring3,
	bip_right_hand_ring4,
	bip_right_in_hand_thumb,
	bip_right_hand_thumb1,
	bip_right_hand_thumb2,
	bip_right_hand_thumb3,
	bip_weapon_container,
	bip_max,
};

#define bip_max_tps bip_left_in_hand_index